name: Flutter Unit And Widget Tests

# Perform action when code is pushed to the main branch
on:
  push:
    branches: [main]

jobs:
  tests:
    # Since the Flutter Local Notification Plugin is only implemented for mobile and not for ubuntu
    # We should run it on MacOS
    runs-on: macOS-latest

    steps:
      # First checkout the new code
      - name: Checkout the code
        uses: actions/checkout@v3

      # Use a handy action from the Github marketplace to install flutter
      - name: Install and set Flutter version
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.6"
          channel: "stable"

      - name: Show Flutter version
        run: flutter --version

      - name: Get Flutter packages
        run: flutter pub get

      - name: Analyze the code
        run: flutter analyze

      - name: Run unit tests with coverage
        run: flutter test --coverage
